ALTER TABLE carritos ALTER COLUMN usuario_id DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_carritos_sesion ON carritos (sesion);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS carrito_id INTEGER REFERENCES carritos(id) ON DELETE SET NULL;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS carrito_vaciado BOOLEAN NOT NULL DEFAULT FALSE;
