ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS stripe_session_id VARCHAR UNIQUE;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS reserva_expira TIMESTAMP;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS reserva_liberada BOOLEAN NOT NULL DEFAULT FALSE;
